name: Build and Push Docker Image

on: 
#   push:
    workflow_dispatch:
      inputs:
        deployment_type:
          description: 'Select deployment strategy'
          required: true
          default: 'normal'
          type: choice
          options:
            - bluegreen
            - canary
            - normal
jobs:
  Build_and_push_image:
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: visits-counter
        IMAGE_TAG: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
            fetch-depth: '1'
            
      - name: Docker_login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build_and_Push_Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    
      - name: Replace_Image_Tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          #!/bash/bin
          git config user.name "github-actions[bot]"
          git config user.email "github-action[bot]@github.com"
          
          # Determine the file path based on deployment type
          if [ "${{ github.event.inputs.deployment_type }}" == "bluegreen" ]; then
            FILE_PATH="./argo_rollouts/bluegreen/blue_green.yaml"
          elif [ "${{ github.event.inputs.deployment_type }}" == "canary" ]; then
            FILE_PATH="./argo_rollouts/canary/canary.yaml"
          elif [ "${{ github.event.inputs.deployment_type }}" == "normal" ]; then
            FILE_PATH="./kubernetes/webapp.yaml"
          fi
          
          sed -i "s|${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:.*|${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" "$FILE_PATH"
          git add "$FILE_PATH"
          git commit -m "Updating the image tag to ${{ env.IMAGE_TAG }} in ${{ github.event.inputs.deployment_type }} deployment"
          git push origin main