name: Build and Push Docker Image

on: 
#   push:
    workflow_dispatch
jobs:
  Build_and_push_image:
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: visits-counter
        IMAGE_TAG: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
            fetch-depth: '1'
            
      - name: Docker_login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build_and_Push_Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    
      - name: Replace_Image_Tag
        run: |
          #!/bash/bin
          git config user.name "github-actions"
          git config user.email "github-action@github.com"
          
          sed -i "s|${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:.*|${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" ./argo_rollouts/bluegreen/blue_green.yaml
          git add ./argo_rollouts/bluegreen/blue_green.yaml
          git commit -m "Updating the image tag to ${{ env.IMAGE_TAG }} in blue_green.yaml file"
          git push origin main